--- #YAML:1.0
name:               Term-Menu-Hierarchical
version:            0.95
abstract:           Perl extension for creating hierarchical menus
author:
    - Ben Okopnik <ben@okopnik.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:           5.007001
    Term::ReadKey:  2.30
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
